[package]
name = "export-enum-demo"
version = "0.1.0"
authors = ["bogay <pojay11523@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = { git = "https://github.com/Bogay/godot-rust", branch = "custom-enum-int" }
